---
title: "Plinth Take-Home Coding Exercise"
subtitle: "Prepared for Nicole Mirea"
format:
  html:
    theme: united
editor: visual
---

# Welcome!

This is a take-home exercise designed to help us understand how you write code and present analysis results.

All of the information you need to complete this exercise should be in this document. But if you have any critical questions you need answers to, feel free to write me at nathaniel@plinth.co!

When you are finished, you should commit your document (and all the code needed to support it) to a new a GitHub repository that you create. If you make it private, be sure to give me access (my github id is ph-nathaniel)

Please complete your work by 9am EST on Monday, May 8. Email me when you are finished with a link to your repository!

## Guidelines

- Do not spend more than 5 hours total. It's ok if you don't get to all of the questions.
- Your final report should be self contained (i.e.; PDF or HTML), with text, outputs, and summaries.
- Focus on quality instead of quantity - a report with a moderate amount of intentional, thoughtful content is much better than one with a lot of disconnected content.
- Write the report as if it will be read by someone with a limited quantitative background, such as a Product Manager or Business Executive.
- Write your code in R, and use any packages you'd like. If possible, please use the tidyverse and not base-R. 
- Feel free to use Google or other online resources, but please don't use ChatGPT or similar AI tools. You may be asked to explain your code later!
- The quality of your code is very important, so make it shine!
- The data you are analyzing are simulated (you'll see details in the documentation), but act as if they are real when you are writing your report.
- There should be no trick questions. However, if you feel you can't answer a question with the data and guidance you were provided, write a brief explanation for what you tried and why you can't answer it and skip it.

# Questions

> Hi Nicole, We are interested in evaluating a new claims dataset for use in answering future Epidemiological and HEOR questions. <br>The data are stored in the github repository https://github.com/Plinth-Analytics/takehome. See the README.md file for details.
> <br> Below, we have a series of questions we would like you to answer using these data. The first set of questions are descriptive and very well specified, while the last question is open-ended. 
> <br>Please remember to keep your overall time below 5 hours!
> <br> Sincerely, <br>Heath Harrington, Project Manager at ACME Pharmaceuticals

*Here are some basic descriptive questions the team would like specific answers to.*

1. How many patients are represented in the data? 
2. How many inpatient claims do we see per patient?
3. What percent of patients have *no* recorded inpatient data?
4. What is the distribution of average prescription costs across patients?
5. What percent of patients have death information?
6. What was the average age of patients at their date of death?
7. What percent of cancer patient’s prescription costs are paid by insurance?
8. Please show us a table of data from 10 randomly sampled patients, include 1 row per patient and a few columns reflecting key patient level variables related to the questions above.

*Here is a core business question the team wants to understand. You are free to answer it any way you'd like*

7. What can these data tell us about the financial impacts of cancer?
<!-- 6. For patients with cancer, what is the affect of diabetes on overall survival? -->

